[build]
    command = "yarn build"
    publish = "dist"

[dev]
    command = "yarn dev"

[[redirects]]
    from = "/cal/:slug"
    to = "https://tidycal.com/sarahsu/:slug"
    status = 301

[[redirects]]
    from = "/"
    to = "/404/"
    status = 404