---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Global Settings
- type: document
  path: src/data/site.json
  label: Site
  match: "**/*"
- type: document
  path: src/data/menu.json
  label: Main Menu
- type: document
  path: src/data/footer.json
  label: Main Footer
- type: heading
  label: Site Data
- type: directory
  path: src/data/pages
  label: Pages
  create: documents
  match: "*.md"
  templates:
  - page
upload_dir: src/assets/images
public_path: "../assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
